services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aparthunter
    ports:
      - "5432:5432"
    volumes:
      - postgres-2:/var/lib/postgresql/data
  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

volumes:
  postgres-2:
  redis: