import YAML from "yaml";
import * as fs from "fs/promises";
import { z } from "zod";
import { format } from "prettier";
import path from "node:path";
import { repoRoot } from "./repoRoot";

const composeSchema = z.object({
  services: z.record(z.any()),
});

const __dirname = new URL(".", import.meta.url).pathname;
const __filename = new URL(import.meta.url).pathname;

const dockerCompose = composeSchema.parse(
  YAML.parse(await fs.readFile(`${repoRoot}/docker-compose.dev.yml`, "utf-8")),
);

const services = Object.keys(dockerCompose.services);

const file = path.join(__dirname, "services.generated.ts");
const schema = `
// This file is generated by ${path.relative(file, __filename)}
export const services = ${JSON.stringify(services)} as const;
`;

await fs.writeFile(
  file,
  await format(schema, {
    filepath: file,
  }),
);
