exports[`getNextJsData > otodom 1`] = `{
  "__typename": "Advert",
  "adCategory": {
    "__typename": "AdvertCategory",
    "id": "101",
    "name": "FLAT",
    "type": "SELL",
  },
  "additionalInformation": [
    {
      "__typename": "AdditionalInfo",
      "label": "market",
      "unit": "",
      "values": [
        "market::secondary",
      ],
    },
    {
      "__typename": "AdditionalInfo",
      "label": "advertiser_type",
      "unit": "",
      "values": [
        "advertiser_type::private",
      ],
    },
    {
      "__typename": "AdditionalInfo",
      "label": "free_from",
      "unit": "",
      "values": [],
    },
    {
      "__typename": "AdditionalInfo",
      "label": "build_year",
      "unit": "",
      "values": [
        "2015",
      ],
    },
    {
      "__typename": "AdditionalInfo",
      "label": "building_type",
      "unit": "",
      "values": [
        "building_type-15::block",
      ],
    },
    {
      "__typename": "AdditionalInfo",
      "label": "windows_type",
      "unit": "",
      "values": [
        "windows_type::plastic",
      ],
    },
    {
      "__typename": "AdditionalInfo",
      "label": "lift",
      "unit": "",
      "values": [
        "::y",
      ],
    },
    {
      "__typename": "AdditionalInfo",
      "label": "media_types",
      "unit": "",
      "values": [
        "media_types::cable-television",
        "media_types::internet",
      ],
    },
    {
      "__typename": "AdditionalInfo",
      "label": "security_types",
      "unit": "",
      "values": [
        "security_types::entryphone",
        "security_types::roller_shutters",
      ],
    },
    {
      "__typename": "AdditionalInfo",
      "label": "equipment_types",
      "unit": "",
      "values": [
        "equipment_types::dishwasher",
        "equipment_types::fridge",
        "equipment_types::furniture",
        "equipment_types::oven",
        "equipment_types::stove",
        "equipment_types::washing_machine",
      ],
    },
    {
      "__typename": "AdditionalInfo",
      "label": "extras_types",
      "unit": "",
      "values": [
        "extras_types::separate_kitchen",
        "extras_types::usable_room",
      ],
    },
    {
      "__typename": "AdditionalInfo",
      "label": "building_material",
      "unit": "",
      "values": [],
    },
  ],
  "advertType": "PRIVATE",
  "advertiserType": "private",
  "agency": null,
  "breadcrumbs": [
    {
      "__typename": "AdvertBreadcrumb",
      "label": "Mieszkanie na sprzedaż",
      "locative": "",
      "url": "https://www.otodom.pl/pl/oferty/sprzedaz/mieszkanie",
    },
    {
      "__typename": "AdvertBreadcrumb",
      "label": "dolnośląskie",
      "locative": "dolnośląskie",
      "url": "https://www.otodom.pl/pl/oferty/sprzedaz/mieszkanie/dolnoslaskie",
    },
    {
      "__typename": "AdvertBreadcrumb",
      "label": "Wrocław",
      "locative": "Wrocław",
      "url": "https://www.otodom.pl/pl/oferty/sprzedaz/mieszkanie/wroclaw",
    },
    {
      "__typename": "AdvertBreadcrumb",
      "label": "Fabryczna",
      "locative": "Fabryczna",
      "url": "https://www.otodom.pl/pl/oferty/sprzedaz/mieszkanie/wroclaw/fabryczna",
    },
    {
      "__typename": "AdvertBreadcrumb",
      "label": "Leśnica",
      "locative": "Leśnica",
      "url": "https://www.otodom.pl/pl/oferty/sprzedaz/mieszkanie/wroclaw/lesnica",
    },
    {
      "__typename": "AdvertBreadcrumb",
      "label": "ul. Alfreda Jahna",
      "locative": "ul. Alfreda Jahna",
      "url": "https://www.otodom.pl/pl/oferty/sprzedaz/mieszkanie/wroclaw?locations%5B0%5D%5BstreetId%5D=93238&locations%5B0%5D%5BcityId%5D=39&locations=%5Bstreets-93238%5D",
    },
    {
      "__typename": "AdvertBreadcrumb",
      "label": "Mieszkanie 3 pokoje z ogródkiem Osiedle Malownicze",
      "locative": "",
      "url": "",
    },
  ],
  "category": {
    "__typename": "AdCategory",
    "id": 101,
    "name": [
      {
        "__typename": "LocalizedString",
        "locale": "pl",
        "value": "Mieszkania",
      },
      {
        "__typename": "LocalizedString",
        "locale": "uk",
        "value": "Квартира",
      },
    ],
  },
  "characteristics": [
    {
      "__typename": "Characteristic",
      "currency": "PLN",
      "key": "price",
      "label": "Cena",
      "localizedValue": "679 000 zł",
      "suffix": "",
      "value": "679000",
    },
    {
      "__typename": "Characteristic",
      "currency": "",
      "key": "m",
      "label": "Powierzchnia",
      "localizedValue": "59 m²",
      "suffix": "",
      "value": "59",
    },
    {
      "__typename": "Characteristic",
      "currency": "",
      "key": "price_per_m",
      "label": "cena za metr",
      "localizedValue": "11 508 zł/m²",
      "suffix": "",
      "value": "11508",
    },
    {
      "__typename": "Characteristic",
      "currency": "",
      "key": "remote_services",
      "label": "Obsługa zdalna",
      "localizedValue": "Tak",
      "suffix": "",
      "value": "1",
    },
    {
      "__typename": "Characteristic",
      "currency": "",
      "key": "rooms_num",
      "label": "Liczba pokoi",
      "localizedValue": "3",
      "suffix": "",
      "value": "3",
    },
    {
      "__typename": "Characteristic",
      "currency": "",
      "key": "market",
      "label": "Rynek",
      "localizedValue": "wtórny",
      "suffix": "",
      "value": "secondary",
    },
    {
      "__typename": "Characteristic",
      "currency": "",
      "key": "building_type",
      "label": "Rodzaj zabudowy",
      "localizedValue": "blok",
      "suffix": "",
      "value": "block",
    },
    {
      "__typename": "Characteristic",
      "currency": "",
      "key": "floor_no",
      "label": "Piętro",
      "localizedValue": "parter",
      "suffix": "",
      "value": "ground_floor",
    },
    {
      "__typename": "Characteristic",
      "currency": "",
      "key": "building_floors_num",
      "label": "Liczba pięter",
      "localizedValue": "3",
      "suffix": "",
      "value": "3",
    },
    {
      "__typename": "Characteristic",
      "currency": "",
      "key": "windows_type",
      "label": "Okna",
      "localizedValue": "plastikowe",
      "suffix": "",
      "value": "plastic",
    },
    {
      "__typename": "Characteristic",
      "currency": "",
      "key": "heating",
      "label": "Ogrzewanie",
      "localizedValue": "kotłownia",
      "suffix": "",
      "value": "boiler_room",
    },
    {
      "__typename": "Characteristic",
      "currency": "",
      "key": "build_year",
      "label": "Rok budowy",
      "localizedValue": "2015",
      "suffix": "",
      "value": "2015",
    },
    {
      "__typename": "Characteristic",
      "currency": "",
      "key": "construction_status",
      "label": "Stan wykończenia",
      "localizedValue": "do zamieszkania",
      "suffix": "",
      "value": "ready_to_use",
    },
    {
      "__typename": "Characteristic",
      "currency": "",
      "key": "building_ownership",
      "label": "Forma własności",
      "localizedValue": "pełna własność",
      "suffix": "",
      "value": "full_ownership",
    },
  ],
  "contactDetails": {
    "imageUrl": "",
    "name": "Irena",
    "phones": [
      "+48505939035",
    ],
    "type": "private",
  },
  "createdAt": "2024-02-10T21:15:19+01:00",
  "creationSource": "none",
  "description": "Sprzedaż bezpośrednio od właściciela.

Sprzedam trzypokojowe, przytulne mieszkanie z ogródkiem, znajdujące na parterze trzypiętrowego budynku, w spokojnej okolicy - na Osiedlu Malowniczym we Wrocławiu. 

W cenie mieszkania ogródek o powierzchni 50 m2. 

Powierzchnia mieszkania to 59 m2.
Salon z wyjściem na ogród. 
Kuchnia w osobnym pomieszczeniu. 
Łazienka z oknem.
Dwie sypialnie.
Przedpokój z zabudowaną wnęką.
Rolety antywłamaniowe we wszystkich oknach i w drzwiach tarasowych.

W budynku znajduje się kotłownia gazowa.

Ponadto do mieszkania przynależy komórka lokatorska (15 000 zł) oraz prywatne miejsce postojowe (25 000 zł). - zakup obligatoryjny. 

Na osiedlu znajduje się sklep Żabka, punkt z pieczywem, stomatolog, klub fitness, dwa paczkomaty, żłobek, plac zabaw. Przystanek autobusowy, z którego można dojechać autobusem do Leśnicy, lub w kierunku Kozanowa/Pilczyc.

Zapraszam do kontaktu. Pośrednikom dziękujemy. 

505 939 035
728 815 541",
  "developmentId": 0,
  "developmentTitle": "",
  "developmentUrl": "",
  "exclusiveOffer": false,
  "externalId": "",
  "features": [
    "telewizja kablowa",
    "internet",
    "domofon / wideofon",
    "rolety antywłamaniowe",
    "zmywarka",
    "lodówka",
    "meble",
    "piekarnik",
    "kuchenka",
    "pralka",
    "garaż/miejsce parkingowe",
    "ogródek",
    "winda",
    "oddzielna kuchnia",
    "taras",
    "pom. użytkowe",
  ],
  "featuresByCategory": [
    {
      "__typename": "FeatureGroup",
      "label": "Media",
      "values": [
        "telewizja kablowa",
        "internet",
      ],
    },
    {
      "__typename": "FeatureGroup",
      "label": "Zabezpieczenia",
      "values": [
        "domofon / wideofon",
        "rolety antywłamaniowe",
      ],
    },
    {
      "__typename": "FeatureGroup",
      "label": "Wyposażenie",
      "values": [
        "zmywarka",
        "lodówka",
        "meble",
        "piekarnik",
        "kuchenka",
        "pralka",
      ],
    },
    {
      "__typename": "FeatureGroup",
      "label": "Informacje dodatkowe",
      "values": [
        "garaż/miejsce parkingowe",
        "ogródek",
        "winda",
        "oddzielna kuchnia",
        "taras",
        "pom. użytkowe",
      ],
    },
  ],
  "featuresWithoutCategory": [],
  "id": 65089808,
  "images": [
    {
      "__typename": "AdImage",
      "large": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6Iml1bXFxbmllZjQzZTMtQVBMIiwidyI6W3siZm4iOiJlbnZmcXFlMWF5NGsxLUFQTCIsInMiOiIxNCIsInAiOiIxMCwtMTAiLCJhIjoiMCJ9XX0.3JS-BXH2Ud0Faub5ttHKpCfcK4B1qOtx3Gw0gwll8Sk/image;s=1280x1024;q=80",
      "medium": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6Iml1bXFxbmllZjQzZTMtQVBMIiwidyI6W3siZm4iOiJlbnZmcXFlMWF5NGsxLUFQTCIsInMiOiIxNCIsInAiOiIxMCwtMTAiLCJhIjoiMCJ9XX0.3JS-BXH2Ud0Faub5ttHKpCfcK4B1qOtx3Gw0gwll8Sk/image;s=655x491;q=80",
      "small": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6Iml1bXFxbmllZjQzZTMtQVBMIiwidyI6W3siZm4iOiJlbnZmcXFlMWF5NGsxLUFQTCIsInMiOiIxNCIsInAiOiIxMCwtMTAiLCJhIjoiMCJ9XX0.3JS-BXH2Ud0Faub5ttHKpCfcK4B1qOtx3Gw0gwll8Sk/image;s=314x236;q=80",
      "thumbnail": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6Iml1bXFxbmllZjQzZTMtQVBMIiwidyI6W3siZm4iOiJlbnZmcXFlMWF5NGsxLUFQTCIsInMiOiIxNCIsInAiOiIxMCwtMTAiLCJhIjoiMCJ9XX0.3JS-BXH2Ud0Faub5ttHKpCfcK4B1qOtx3Gw0gwll8Sk/image;s=184x138;q=80",
    },
    {
      "__typename": "AdImage",
      "large": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6InUydHg5dGg1OHc2dTMtQVBMIiwidyI6W3siZm4iOiJlbnZmcXFlMWF5NGsxLUFQTCIsInMiOiIxNCIsInAiOiIxMCwtMTAiLCJhIjoiMCJ9XX0.tW7FVDJgk7lYDy7Uhstg7x5BvWpmxcsXVtVqpVEXSMc/image;s=1280x1024;q=80",
      "medium": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6InUydHg5dGg1OHc2dTMtQVBMIiwidyI6W3siZm4iOiJlbnZmcXFlMWF5NGsxLUFQTCIsInMiOiIxNCIsInAiOiIxMCwtMTAiLCJhIjoiMCJ9XX0.tW7FVDJgk7lYDy7Uhstg7x5BvWpmxcsXVtVqpVEXSMc/image;s=655x491;q=80",
      "small": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6InUydHg5dGg1OHc2dTMtQVBMIiwidyI6W3siZm4iOiJlbnZmcXFlMWF5NGsxLUFQTCIsInMiOiIxNCIsInAiOiIxMCwtMTAiLCJhIjoiMCJ9XX0.tW7FVDJgk7lYDy7Uhstg7x5BvWpmxcsXVtVqpVEXSMc/image;s=314x236;q=80",
      "thumbnail": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6InUydHg5dGg1OHc2dTMtQVBMIiwidyI6W3siZm4iOiJlbnZmcXFlMWF5NGsxLUFQTCIsInMiOiIxNCIsInAiOiIxMCwtMTAiLCJhIjoiMCJ9XX0.tW7FVDJgk7lYDy7Uhstg7x5BvWpmxcsXVtVqpVEXSMc/image;s=184x138;q=80",
    },
    {
      "__typename": "AdImage",
      "large": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6Im1qd2QwaGo4dnpqazMtQVBMIiwidyI6W3siZm4iOiJlbnZmcXFlMWF5NGsxLUFQTCIsInMiOiIxNCIsInAiOiIxMCwtMTAiLCJhIjoiMCJ9XX0.yMTByyGZ-NA-dfdwiWn5hs_6G-1NxTCqJ2yHyoa26QM/image;s=1280x1024;q=80",
      "medium": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6Im1qd2QwaGo4dnpqazMtQVBMIiwidyI6W3siZm4iOiJlbnZmcXFlMWF5NGsxLUFQTCIsInMiOiIxNCIsInAiOiIxMCwtMTAiLCJhIjoiMCJ9XX0.yMTByyGZ-NA-dfdwiWn5hs_6G-1NxTCqJ2yHyoa26QM/image;s=655x491;q=80",
      "small": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6Im1qd2QwaGo4dnpqazMtQVBMIiwidyI6W3siZm4iOiJlbnZmcXFlMWF5NGsxLUFQTCIsInMiOiIxNCIsInAiOiIxMCwtMTAiLCJhIjoiMCJ9XX0.yMTByyGZ-NA-dfdwiWn5hs_6G-1NxTCqJ2yHyoa26QM/image;s=314x236;q=80",
      "thumbnail": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6Im1qd2QwaGo4dnpqazMtQVBMIiwidyI6W3siZm4iOiJlbnZmcXFlMWF5NGsxLUFQTCIsInMiOiIxNCIsInAiOiIxMCwtMTAiLCJhIjoiMCJ9XX0.yMTByyGZ-NA-dfdwiWn5hs_6G-1NxTCqJ2yHyoa26QM/image;s=184x138;q=80",
    },
    {
      "__typename": "AdImage",
      "large": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6IjIzbWZheTVqZWo1cy1BUEwiLCJ3IjpbeyJmbiI6ImVudmZxcWUxYXk0azEtQVBMIiwicyI6IjE0IiwicCI6IjEwLC0xMCIsImEiOiIwIn1dfQ.MNTjhInomPDwZBJeDWHG7KYAi3DQj8bgav7wPPNoTaY/image;s=1280x1024;q=80",
      "medium": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6IjIzbWZheTVqZWo1cy1BUEwiLCJ3IjpbeyJmbiI6ImVudmZxcWUxYXk0azEtQVBMIiwicyI6IjE0IiwicCI6IjEwLC0xMCIsImEiOiIwIn1dfQ.MNTjhInomPDwZBJeDWHG7KYAi3DQj8bgav7wPPNoTaY/image;s=655x491;q=80",
      "small": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6IjIzbWZheTVqZWo1cy1BUEwiLCJ3IjpbeyJmbiI6ImVudmZxcWUxYXk0azEtQVBMIiwicyI6IjE0IiwicCI6IjEwLC0xMCIsImEiOiIwIn1dfQ.MNTjhInomPDwZBJeDWHG7KYAi3DQj8bgav7wPPNoTaY/image;s=314x236;q=80",
      "thumbnail": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6IjIzbWZheTVqZWo1cy1BUEwiLCJ3IjpbeyJmbiI6ImVudmZxcWUxYXk0azEtQVBMIiwicyI6IjE0IiwicCI6IjEwLC0xMCIsImEiOiIwIn1dfQ.MNTjhInomPDwZBJeDWHG7KYAi3DQj8bgav7wPPNoTaY/image;s=184x138;q=80",
    },
    {
      "__typename": "AdImage",
      "large": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6ImRzamIya2FnbHU2dzItQVBMIiwidyI6W3siZm4iOiJlbnZmcXFlMWF5NGsxLUFQTCIsInMiOiIxNCIsInAiOiIxMCwtMTAiLCJhIjoiMCJ9XX0.fcAqUvGlrmOovIEOdkoc4I12ETbz1ybOILsCVdDc7_I/image;s=1280x1024;q=80",
      "medium": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6ImRzamIya2FnbHU2dzItQVBMIiwidyI6W3siZm4iOiJlbnZmcXFlMWF5NGsxLUFQTCIsInMiOiIxNCIsInAiOiIxMCwtMTAiLCJhIjoiMCJ9XX0.fcAqUvGlrmOovIEOdkoc4I12ETbz1ybOILsCVdDc7_I/image;s=655x491;q=80",
      "small": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6ImRzamIya2FnbHU2dzItQVBMIiwidyI6W3siZm4iOiJlbnZmcXFlMWF5NGsxLUFQTCIsInMiOiIxNCIsInAiOiIxMCwtMTAiLCJhIjoiMCJ9XX0.fcAqUvGlrmOovIEOdkoc4I12ETbz1ybOILsCVdDc7_I/image;s=314x236;q=80",
      "thumbnail": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6ImRzamIya2FnbHU2dzItQVBMIiwidyI6W3siZm4iOiJlbnZmcXFlMWF5NGsxLUFQTCIsInMiOiIxNCIsInAiOiIxMCwtMTAiLCJhIjoiMCJ9XX0.fcAqUvGlrmOovIEOdkoc4I12ETbz1ybOILsCVdDc7_I/image;s=184x138;q=80",
    },
    {
      "__typename": "AdImage",
      "large": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6ImloMnAyODZoa2M5MzItQVBMIiwidyI6W3siZm4iOiJlbnZmcXFlMWF5NGsxLUFQTCIsInMiOiIxNCIsInAiOiIxMCwtMTAiLCJhIjoiMCJ9XX0.VDZ7OhrtIebpp8nLm_dWO3BbTYI676v8hpSn3XRWdow/image;s=1280x1024;q=80",
      "medium": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6ImloMnAyODZoa2M5MzItQVBMIiwidyI6W3siZm4iOiJlbnZmcXFlMWF5NGsxLUFQTCIsInMiOiIxNCIsInAiOiIxMCwtMTAiLCJhIjoiMCJ9XX0.VDZ7OhrtIebpp8nLm_dWO3BbTYI676v8hpSn3XRWdow/image;s=655x491;q=80",
      "small": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6ImloMnAyODZoa2M5MzItQVBMIiwidyI6W3siZm4iOiJlbnZmcXFlMWF5NGsxLUFQTCIsInMiOiIxNCIsInAiOiIxMCwtMTAiLCJhIjoiMCJ9XX0.VDZ7OhrtIebpp8nLm_dWO3BbTYI676v8hpSn3XRWdow/image;s=314x236;q=80",
      "thumbnail": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6ImloMnAyODZoa2M5MzItQVBMIiwidyI6W3siZm4iOiJlbnZmcXFlMWF5NGsxLUFQTCIsInMiOiIxNCIsInAiOiIxMCwtMTAiLCJhIjoiMCJ9XX0.VDZ7OhrtIebpp8nLm_dWO3BbTYI676v8hpSn3XRWdow/image;s=184x138;q=80",
    },
    {
      "__typename": "AdImage",
      "large": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6ImZsMnd2cHY5bGE5dS1BUEwiLCJ3IjpbeyJmbiI6ImVudmZxcWUxYXk0azEtQVBMIiwicyI6IjE0IiwicCI6IjEwLC0xMCIsImEiOiIwIn1dfQ.3cmyVu_9CMprl5OKvMv3MQfv01hkZh2b1XtZP7XgClc/image;s=1280x1024;q=80",
      "medium": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6ImZsMnd2cHY5bGE5dS1BUEwiLCJ3IjpbeyJmbiI6ImVudmZxcWUxYXk0azEtQVBMIiwicyI6IjE0IiwicCI6IjEwLC0xMCIsImEiOiIwIn1dfQ.3cmyVu_9CMprl5OKvMv3MQfv01hkZh2b1XtZP7XgClc/image;s=655x491;q=80",
      "small": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6ImZsMnd2cHY5bGE5dS1BUEwiLCJ3IjpbeyJmbiI6ImVudmZxcWUxYXk0azEtQVBMIiwicyI6IjE0IiwicCI6IjEwLC0xMCIsImEiOiIwIn1dfQ.3cmyVu_9CMprl5OKvMv3MQfv01hkZh2b1XtZP7XgClc/image;s=314x236;q=80",
      "thumbnail": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6ImZsMnd2cHY5bGE5dS1BUEwiLCJ3IjpbeyJmbiI6ImVudmZxcWUxYXk0azEtQVBMIiwicyI6IjE0IiwicCI6IjEwLC0xMCIsImEiOiIwIn1dfQ.3cmyVu_9CMprl5OKvMv3MQfv01hkZh2b1XtZP7XgClc/image;s=184x138;q=80",
    },
    {
      "__typename": "AdImage",
      "large": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6Ing4YW1wOGE0eDk3bjItQVBMIiwidyI6W3siZm4iOiJlbnZmcXFlMWF5NGsxLUFQTCIsInMiOiIxNCIsInAiOiIxMCwtMTAiLCJhIjoiMCJ9XX0.-8uVvrBx8Fpi9AzGJH7_gmzqQPeik335iUCEvzUDVyY/image;s=1280x1024;q=80",
      "medium": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6Ing4YW1wOGE0eDk3bjItQVBMIiwidyI6W3siZm4iOiJlbnZmcXFlMWF5NGsxLUFQTCIsInMiOiIxNCIsInAiOiIxMCwtMTAiLCJhIjoiMCJ9XX0.-8uVvrBx8Fpi9AzGJH7_gmzqQPeik335iUCEvzUDVyY/image;s=655x491;q=80",
      "small": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6Ing4YW1wOGE0eDk3bjItQVBMIiwidyI6W3siZm4iOiJlbnZmcXFlMWF5NGsxLUFQTCIsInMiOiIxNCIsInAiOiIxMCwtMTAiLCJhIjoiMCJ9XX0.-8uVvrBx8Fpi9AzGJH7_gmzqQPeik335iUCEvzUDVyY/image;s=314x236;q=80",
      "thumbnail": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6Ing4YW1wOGE0eDk3bjItQVBMIiwidyI6W3siZm4iOiJlbnZmcXFlMWF5NGsxLUFQTCIsInMiOiIxNCIsInAiOiIxMCwtMTAiLCJhIjoiMCJ9XX0.-8uVvrBx8Fpi9AzGJH7_gmzqQPeik335iUCEvzUDVyY/image;s=184x138;q=80",
    },
    {
      "__typename": "AdImage",
      "large": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6IjZja3UwZG0zZXJmYjEtQVBMIiwidyI6W3siZm4iOiJlbnZmcXFlMWF5NGsxLUFQTCIsInMiOiIxNCIsInAiOiIxMCwtMTAiLCJhIjoiMCJ9XX0.f7SKnkeqEcyTmwg0qimTZNfDEWwKnntiNJXX5Una4sQ/image;s=1280x1024;q=80",
      "medium": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6IjZja3UwZG0zZXJmYjEtQVBMIiwidyI6W3siZm4iOiJlbnZmcXFlMWF5NGsxLUFQTCIsInMiOiIxNCIsInAiOiIxMCwtMTAiLCJhIjoiMCJ9XX0.f7SKnkeqEcyTmwg0qimTZNfDEWwKnntiNJXX5Una4sQ/image;s=655x491;q=80",
      "small": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6IjZja3UwZG0zZXJmYjEtQVBMIiwidyI6W3siZm4iOiJlbnZmcXFlMWF5NGsxLUFQTCIsInMiOiIxNCIsInAiOiIxMCwtMTAiLCJhIjoiMCJ9XX0.f7SKnkeqEcyTmwg0qimTZNfDEWwKnntiNJXX5Una4sQ/image;s=314x236;q=80",
      "thumbnail": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6IjZja3UwZG0zZXJmYjEtQVBMIiwidyI6W3siZm4iOiJlbnZmcXFlMWF5NGsxLUFQTCIsInMiOiIxNCIsInAiOiIxMCwtMTAiLCJhIjoiMCJ9XX0.f7SKnkeqEcyTmwg0qimTZNfDEWwKnntiNJXX5Una4sQ/image;s=184x138;q=80",
    },
    {
      "__typename": "AdImage",
      "large": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6IjEzaWVuNzNueDJ3cDMtQVBMIiwidyI6W3siZm4iOiJlbnZmcXFlMWF5NGsxLUFQTCIsInMiOiIxNCIsInAiOiIxMCwtMTAiLCJhIjoiMCJ9XX0.7YAjv_JLCkJNyYI82L-aC8zIPuAtCahoZFVj0n6H9jQ/image;s=1280x1024;q=80",
      "medium": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6IjEzaWVuNzNueDJ3cDMtQVBMIiwidyI6W3siZm4iOiJlbnZmcXFlMWF5NGsxLUFQTCIsInMiOiIxNCIsInAiOiIxMCwtMTAiLCJhIjoiMCJ9XX0.7YAjv_JLCkJNyYI82L-aC8zIPuAtCahoZFVj0n6H9jQ/image;s=655x491;q=80",
      "small": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6IjEzaWVuNzNueDJ3cDMtQVBMIiwidyI6W3siZm4iOiJlbnZmcXFlMWF5NGsxLUFQTCIsInMiOiIxNCIsInAiOiIxMCwtMTAiLCJhIjoiMCJ9XX0.7YAjv_JLCkJNyYI82L-aC8zIPuAtCahoZFVj0n6H9jQ/image;s=314x236;q=80",
      "thumbnail": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6IjEzaWVuNzNueDJ3cDMtQVBMIiwidyI6W3siZm4iOiJlbnZmcXFlMWF5NGsxLUFQTCIsInMiOiIxNCIsInAiOiIxMCwtMTAiLCJhIjoiMCJ9XX0.7YAjv_JLCkJNyYI82L-aC8zIPuAtCahoZFVj0n6H9jQ/image;s=184x138;q=80",
    },
    {
      "__typename": "AdImage",
      "large": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6ImE3N241Znk2dm9mNy1BUEwiLCJ3IjpbeyJmbiI6ImVudmZxcWUxYXk0azEtQVBMIiwicyI6IjE0IiwicCI6IjEwLC0xMCIsImEiOiIwIn1dfQ.NIjp00--8myHHdfy7F1kd2VDttN-Cx1MWp5yLc2Vqqk/image;s=1280x1024;q=80",
      "medium": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6ImE3N241Znk2dm9mNy1BUEwiLCJ3IjpbeyJmbiI6ImVudmZxcWUxYXk0azEtQVBMIiwicyI6IjE0IiwicCI6IjEwLC0xMCIsImEiOiIwIn1dfQ.NIjp00--8myHHdfy7F1kd2VDttN-Cx1MWp5yLc2Vqqk/image;s=655x491;q=80",
      "small": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6ImE3N241Znk2dm9mNy1BUEwiLCJ3IjpbeyJmbiI6ImVudmZxcWUxYXk0azEtQVBMIiwicyI6IjE0IiwicCI6IjEwLC0xMCIsImEiOiIwIn1dfQ.NIjp00--8myHHdfy7F1kd2VDttN-Cx1MWp5yLc2Vqqk/image;s=314x236;q=80",
      "thumbnail": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6ImE3N241Znk2dm9mNy1BUEwiLCJ3IjpbeyJmbiI6ImVudmZxcWUxYXk0azEtQVBMIiwicyI6IjE0IiwicCI6IjEwLC0xMCIsImEiOiIwIn1dfQ.NIjp00--8myHHdfy7F1kd2VDttN-Cx1MWp5yLc2Vqqk/image;s=184x138;q=80",
    },
  ],
  "links": {
    "__typename": "AdvertLinks",
    "localPlanUrl": "",
    "videoUrl": "",
    "view3dUrl": "",
    "walkaroundUrl": "",
  },
  "location": {
    "__typename": "LocationDetails",
    "address": {
      "__typename": "Address",
      "city": {
        "__typename": "City",
        "code": "wroclaw",
        "id": "39",
        "name": "Wrocław",
      },
      "county": {
        "__typename": "County",
        "code": "powiat-wroclaw",
        "id": "381",
        "name": "Wrocław",
      },
      "district": {
        "__typename": "District",
        "code": "lesnica",
        "id": "1833",
        "name": "Leśnica",
      },
      "municipality": null,
      "postalCode": null,
      "province": {
        "__typename": "Province",
        "code": "dolnoslaskie",
        "id": "1",
        "name": "dolnośląskie",
      },
      "street": {
        "__typename": "Street",
        "code": "",
        "id": "93238",
        "name": "ul. Alfreda Jahna",
        "number": "",
      },
      "subdistrict": null,
    },
    "coordinates": {
      "__typename": "Coordinates",
      "latitude": 51.1616158,
      "longitude": 16.8734874,
    },
    "id": null,
    "mapDetails": {
      "__typename": "MapDetails",
      "radius": 0,
      "zoom": 16,
    },
    "reverseGeocoding": {
      "__typename": "ReverseGeocoding",
      "locations": [
        {
          "__typename": "BasicLocationObject",
          "fullName": "dolnośląskie",
          "fullNameItems": [
            "dolnośląskie",
          ],
          "id": "dolnoslaskie",
          "locationLevel": "voivodeship",
          "name": "dolnośląskie",
          "parentIds": [],
        },
        {
          "__typename": "BasicLocationObject",
          "fullName": "Wrocław, dolnośląskie",
          "fullNameItems": [
            "Wrocław",
            "dolnośląskie",
          ],
          "id": "dolnoslaskie/wroclaw/wroclaw/wroclaw",
          "locationLevel": "city_or_village",
          "name": "Wrocław",
          "parentIds": [
            "dolnoslaskie",
            "dolnoslaskie/wroclaw",
            "dolnoslaskie/wroclaw/wroclaw",
          ],
        },
        {
          "__typename": "BasicLocationObject",
          "fullName": "Fabryczna, Wrocław, dolnośląskie",
          "fullNameItems": [
            "Fabryczna",
            "Wrocław",
            "dolnośląskie",
          ],
          "id": "dolnoslaskie/wroclaw/wroclaw/wroclaw/fabryczna",
          "locationLevel": "district",
          "name": "Fabryczna",
          "parentIds": [
            "dolnoslaskie",
            "dolnoslaskie/wroclaw",
            "dolnoslaskie/wroclaw/wroclaw",
            "dolnoslaskie/wroclaw/wroclaw/wroclaw",
          ],
        },
        {
          "__typename": "BasicLocationObject",
          "fullName": "Leśnica, Fabryczna, Wrocław, dolnośląskie",
          "fullNameItems": [
            "Leśnica",
            "Fabryczna",
            "Wrocław",
            "dolnośląskie",
          ],
          "id": "dolnoslaskie/wroclaw/wroclaw/wroclaw/fabryczna/lesnica",
          "locationLevel": "residential",
          "name": "Leśnica",
          "parentIds": [
            "dolnoslaskie",
            "dolnoslaskie/wroclaw",
            "dolnoslaskie/wroclaw/wroclaw",
            "dolnoslaskie/wroclaw/wroclaw/wroclaw",
            "dolnoslaskie/wroclaw/wroclaw/wroclaw/fabryczna",
          ],
        },
      ],
    },
  },
  "market": "SECONDARY",
  "modifiedAt": "2024-03-11T21:18:41+01:00",
  "openDay": null,
  "owner": {
    "__typename": "LegacyAdvertOwner",
    "contacts": [],
    "id": 9860863,
    "imageUrl": "",
    "name": "Irena",
    "phones": [
      "+48505939035",
    ],
    "type": "private",
  },
  "paginatedUnits": {
    "__typename": "AdvertsPages",
    "facets": null,
    "isPriceHidden": null,
    "items": null,
    "pagination": null,
  },
  "price": {
    "__typename": "AdvertPrice",
    "type": "",
  },
  "property": {
    "__typename": "Flat",
    "area": {
      "__typename": "Area",
      "unit": "M2",
      "value": 59,
    },
    "buildingProperties": {
      "__typename": "FlatBuildingProperties",
      "conveniences": [
        "LIFT",
        "INTERNET",
      ],
      "heating": "BOILER_ROOM",
      "material": null,
      "numberOfFloors": 3,
      "security": [
        "ENTRYPHONE",
        "ROLLER_SHUTTERS",
      ],
      "type": "BLOCK",
      "windows": [
        "PLASTIC",
      ],
      "year": 2015,
    },
    "condition": "READY_TO_USE",
    "costs": [],
    "id": null,
    "ownership": "FULL_OWNERSHIP",
    "properties": {
      "__typename": "FlatProperties",
      "areas": [
        "garage",
        "garden",
        "terrace",
        "usable_room",
      ],
      "equipment": [
        "dishwasher",
        "fridge",
        "furniture",
        "oven",
        "stove",
        "washing_machine",
      ],
      "floor": "GROUND_FLOOR",
      "kitchen": "SEPARATE",
      "numberOfRooms": 3,
      "parking": [],
      "rooms": [],
      "type": null,
      "windowsOrientation": [],
    },
    "rent": null,
    "type": "FLAT",
  },
  "publicId": "",
  "referenceId": "",
  "seo": {
    "__typename": "AdvertSeo",
    "description": "Świetne 3 pokojowe mieszkanie na sprzedaż w miejscowości Wrocław, Fabryczna, Leśnica, za cenę 679 000 zł. To mieszkanie na sprzedaż  na parter piętrze ma 59 m² powierzchni użytkowej i 59 m² powierzchni całkowitej. Właściciel jako najważniejsze zalety mieszkania wymienia: garaż/miejsce parkingowe, ogródek, winda. Otodom 65089808",
    "title": "Archiwalne: 3 pokoje, mieszkanie na sprzedaż - Wrocław, Fabryczna, Leśnica - 65089808 • www.otodom.pl",
  },
  "services": [
    "E_SIGNATURE",
    "VIDEO_PRESENTATION",
    "VIDEO_MEETING",
  ],
  "shouldShowExpiredAdPage": true,
  "similarAdsLinkUrl": "/pl/wyniki/sprzedaz/mieszkanie/dolnoslaskie/wroclaw/wroclaw/wroclaw/fabryczna/lesnica",
  "slug": "mieszkanie-3-pokoje-z-ogrodkiem-osiedle-malownicze-ID4p6PC",
  "source": "urn:site:local",
  "specialOffer": null,
  "status": "removed_by_user",
  "target": {
    "Area": "59",
    "AreaRange": [],
    "Build_year": "2015",
    "Building_floors_num": "3",
    "Building_ownership": [
      "full_ownership",
    ],
    "Building_type": [
      "block",
    ],
    "City": "wroclaw",
    "City_id": "39",
    "Construction_status": [
      "ready_to_use",
    ],
    "Country": "Polska",
    "Equipment_types": [
      "dishwasher",
      "fridge",
      "furniture",
      "oven",
      "stove",
      "washing_machine",
    ],
    "Extras_types": [
      "garage",
      "garden",
      "lift",
      "separate_kitchen",
      "terrace",
      "usable_room",
    ],
    "Floor_no": [
      "ground_floor",
    ],
    "Heating": [
      "boiler_room",
    ],
    "Id": "65089808",
    "MarketType": "secondary",
    "Media_types": [
      "cable-television",
      "internet",
    ],
    "ObidoAdvert": "n",
    "OfferType": "sprzedaz",
    "Photo": "aHR0cHM6Ly9pcmVsYW5kLmFwb2xsby5vbHhjZG4uY29tL3YxL2ZpbGVzL2V5Sm1iaUk2SW1sMWJYRnhibWxsWmpRelpUTXRRVkJNSWl3aWR5STZXM3NpWm00aU9pSmxiblptY1hGbE1XRjVOR3N4TFVGUVRDSXNJbk1pT2lJeE5DSXNJbkFpT2lJeE1Dd3RNVEFpTENKaElqb2lNQ0o5WFgwLjNKUy1CWEgyVWQwRmF1YjV0dEhLcENmY0s0QjFxT3R4M0d3MGd3bGw4U2svaW1hZ2U7cz02NTV4NDkxO3E9ODA=",
    "Price": 679000,
    "PriceRange": [
      "500001-750000",
    ],
    "Price_per_m": 11508,
    "ProperType": "mieszkanie",
    "Province": "dolnoslaskie",
    "RegularUser": "y",
    "Remote_services": [
      "1",
    ],
    "Rooms_num": [
      "3",
    ],
    "Security_types": [
      "entryphone",
      "roller_shutters",
    ],
    "Subregion": "powiat-wroclaw",
    "Title": "TWllc3prYW5pZSAzIHBva29qZSB6IG9ncsOzZGtpZW0gT3NpZWRsZSBNYWxvd25pY3pl",
    "Windows_type": [
      "plastic",
    ],
    "categoryId": "101",
    "env": "production",
    "hidePrice": "0",
    "seller_id": "9860863",
    "user_type": "private",
  },
  "title": "Mieszkanie 3 pokoje z ogródkiem Osiedle Malownicze",
  "topInformation": [
    {
      "__typename": "AdditionalInfo",
      "label": "area",
      "unit": "m²",
      "values": [
        "59",
      ],
    },
    {
      "__typename": "AdditionalInfo",
      "label": "building_ownership",
      "unit": "",
      "values": [
        "building_ownership::full_ownership",
      ],
    },
    {
      "__typename": "AdditionalInfo",
      "label": "rooms_num",
      "unit": "",
      "values": [
        "3",
      ],
    },
    {
      "__typename": "AdditionalInfo",
      "label": "construction_status",
      "unit": "",
      "values": [
        "construction_status-67::ready_to_use",
      ],
    },
    {
      "__typename": "AdditionalInfo",
      "label": "floor",
      "unit": "",
      "values": [
        "floor_no::ground_floor",
        "/3",
      ],
    },
    {
      "__typename": "AdditionalInfo",
      "label": "outdoor",
      "unit": "",
      "values": [
        "extras_types::garden",
        "extras_types::terrace",
      ],
    },
    {
      "__typename": "AdditionalInfo",
      "label": "rent",
      "unit": "",
      "values": [],
    },
    {
      "__typename": "AdditionalInfo",
      "label": "car",
      "unit": "",
      "values": [
        "extras_types-85::garage",
      ],
    },
    {
      "__typename": "AdditionalInfo",
      "label": "remote_services",
      "unit": "",
      "values": [
        "remote_services::1",
      ],
    },
    {
      "__typename": "AdditionalInfo",
      "label": "heating",
      "unit": "",
      "values": [
        "heating::boiler_room",
      ],
    },
  ],
  "url": "https://www.otodom.pl/pl/oferta/mieszkanie-3-pokoje-z-ogrodkiem-osiedle-malownicze-ID4p6PC",
  "userAdverts": [],
}`
